joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

# ... below the joy parameters

teleop_drive_node: #teleop_drive_node
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 1 #4
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0 #3
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 3.0

    require_enable_button: true
    enable_button: 4 # Left shoulder button
    enable_turbo_button: 2  # Right shoulder button


# joy_teleop_node:
#   ros__parameters:
#     camera_control:
#       type: topic
#       message_type: std_msgs/Float64
#       topic_name: /camera_joint/velocity_controller/command
#       axis_mappings:
#         - axis: 3  # Right thumb stick horizontal axis
#           scale: 0.5  # Adjust this value as necessary to control the speed
#       enable_buttons: [3]  # Right shoulder button to enable camera control


joy_teleop_node:
  ros__parameters:
    camera_control:
      type: topic
      interface_type: std_msgs/msg/Float64  # Correctly specify the interface type
      topic_name: /camera_joint/velocity_controller/command
      axis_mappings:
          axis: 3  # Right thumb stick horizontal
          target: data
          scale: 1.0
      deadman_buttons: [5]  # Right shoulder butto
