controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    camera_joint_controller:  # Add this section
      type: "velocity_controllers/JointGroupVelocityController"  # Ensure the type is correct
      joints: 
        - "camera_joint"

diff_cont:
  ros__parameters:

    publish_rate: 30.0
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.245
    wheel_radius: 0.0675

    use_stamped_vel: false

camera_joint_controller:
  ros__parameters:
    type: "velocity_controllers/JointGroupVelocityController"
    joints:
      - "camera_joint"
    command_interfaces: ["velocity"]
    state_interfaces: ["velocity", "position"]

# camera_joint_controller:
#   ros__parameters:
#     publish_rate: 30.0
#     base_frame_id: base_link

#     camera_joint_name: ['camera_joint']

#     use_stamped_vel: false